### ISSUE TITLE
Missing file `armeabi-v7a/lib/libboost_signals.a` on branch ` boost-1_72_0`

### ISSUE THREAD

**Issue by rohitdwivedula** [PurpleI2P/Boost-for-Android-Prebuilt#4]
It looks like one compiled file, `libboost_signals.a` is missing for boost `v1.72.0`. Not sure if I'm doing anything wrong, but just thought I'd leave a heads up here incase anyone else tries to use that version (and needs `libboost_signals`). 

This is what my root `Android.mk` looks like:

```
MY_PATH := $(call my-dir)
include $(MY_PATH)/boost-1_72_0/Android.mk

LOCAL_PATH := $(JNI_PATH)

include $(CLEAR_VARS)
LOCAL_MODULE := <my module name here>
LOCAL_SRC_FILES := <list of files>
LOCAL_LDLIBS += -llog
LOCAL_CPPFLAGS += -std=c++11

LOCAL_SHARED_LIBRARIES := boost
include $(BUILD_SHARED_LIBRARY)
```

I tried `LOCAL_SHARED_LIBRARIES=boost` and `LOCAL_SHARED_LIBRARIES=boost*` with Android NDK 21, and both versions of the `Android.mk` led to an error that looked like this:

```
Android NDK: ERROR:/path/to/my/app/jni/boost-1_72_0/Android.mk:boost_signals: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /path/to/my/app/jni/boost-1_72_0/armeabi-v7a/lib/libboost_signals.a exists  or that its path is correct   
```

Looking at that directory [in this repo](https://github.com/PurpleI2P/Boost-for-Android-Prebuilt/tree/boost-1_72_0/boost-1_72_0/armeabi-v7a/lib), it does indeed appear that `libboost_signals.a` does not exist.

**Comment by r4sas** [comment]
You can remove that module defenition because it has no library and based on headers.
