### ISSUE TITLE
need help for configuring jni cMake project

### ISSUE THREAD

**Issue by AhmedX6** [PurpleI2P/Boost-for-Android-Prebuilt#5]
Hello,

I would like to have some help for CMake based JNI project on Android App.

Is it possible to have a readme how to integrate boost ?

thanks.

**Comment by r4sas** [comment]
Hello.
I never used jni with CMake, so can't help you. See here, maybe that helps you: https://github.com/moritz-wundke/Boost-for-Android/issues/199
