### ISSUE TITLE
ld: error: undefined symbol: boost::throw_exception

### ISSUE THREAD

**Issue by AhmedX6** [PurpleI2P/Boost-for-Android-Prebuilt#6]
Hello,

I finally migrated to Android.mk + Application.mk file.

I have an issue on building my project with some boost calls (regex).

![image](https://user-images.githubusercontent.com/13573148/169672536-06e1bff1-2d71-4968-885c-2200cda4f2a7.png)

```
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE    			:=  helperEngine
LOCAL_MODULE_FILENAME 		:= 	libhelperEngine
LOCAL_SRC_FILES 			:= 	test.cpp
LOCAL_CPP_EXTENSION 		:= 	.cxx .cpp .cc
LOCAL_CPPFLAGS 				:= 	-D__ANDROID__ -DBOOST_NO_EXCEPTIONS
LOCAL_LDLIBS 				:= 	-llog
LOCAL_C_INCLUDES			:= 	$(LOCAL_PATH)/boost/boost-1_72_0/include
LOCAL_STATIC_LIBRARIES 		:= 	libboost_system \
								libboost_thread \
							   	libboost_context \
							   	libboost_exception \
							   	libboost_container \
							   	libboost_regex \
							   	libboost_atomic \
							   	libboost_chrono
```

```
APP_ABI := x86 x86_64 armeabi-v7a arm64-v8a
APP_STL := c++_static
APP_CLANG_TIDY := false
APP_BUILD_SCRIPT := Android.mk
APP_CPPFLAGS += -std=c++14
```

Need help..
Thanks

I'm using ND24 and boost 1.72 prebuilt.

**Comment by r4sas** [comment]
Look at our libraries and code defining: https://github.com/PurpleI2P/i2pd-android/blob/master/app/jni/Android.mk

**Comment by AhmedX6** [comment]
Ok I see that you're rebuilding boost with a script build-boost.sh, I'm using your prebuilt here. Is it possible for you to push the prebuilt for 1.78 or at least 1.74 on a branch?

The compilation of boost 1.74 failing on my side with on bootstrap.log `unknown toolset vcunk`, indeed on my machine I got only visual code build tools 2022 and only boost 1.78 is supporting vcunk it seems.

That would be good, if you got the 1.78 prebuilt. Thanks for your help

I will try to build 1.78 right now to see if it works

**Comment by r4sas** [comment]
I'll try to build it, but bit later.

What about `vcunk`, change `boost-android.sh` script here:

https://github.com/moritz-wundke/Boost-for-Android/blob/0e12fbd30cb70b668a117c0913a303acfdaae04f/build-android.sh#L481

Add `gcc`, so it will look like `"bootstrap.bat gcc"` and use MSYS2.

If didn't want to use it, check boost's `bootstrap.cmd` contents to find workaround.

**Comment by AhmedX6** [comment]
Finally I succeed build 1.78 with your script only on libraries : `date_time,filesystem,program_options,system,regex,json` with ndk23.

Could you try to build with all libraries on your side and let me know if you succeed and maybe create a branch for it :)

Thanks a lot for your help.

Little question : does include folder could be factorized? Or include folder is different for each architecture?

**Comment by r4sas** [comment]
Pushed `boost-1_78_0` branch.

> Little question : does include folder could be factorized? Or include folder is different for each architecture?

`diff` says they are the same, so I only add the libraries in the <arch> subdirectories to the repository and only one `include` next to them.

**Comment by AhmedX6** [comment]
Thanksss a lot for your branch will use these prebuilts then...

Maybe I'll contact you for further updates if needed 🥇
